# Generated by Django 4.2.26 on 2025-12-23 18:20

import core.fields
import core.models.base_mutation
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import medical_pricelist.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_remove_healthfacilitycontract_uq_hf_loc_contract_valid_and_more'),
        ('core', '0032_create_tblclaimadmin'),
        ('medical', '0012_laboratoryservice_alter_service_care_type_and_more'),
        ('medical_pricelist', '0004_set_managed_to_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryServicesPricelist',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PLLabServiceID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PLLabServiceUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('name', models.CharField(db_column='PLLabServiceName', max_length=100)),
                ('pricelist_date', core.fields.DateField(db_column='DatePL')),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('location', models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_services_pricelists', to='location.location')),
            ],
            options={
                'db_table': 'tblPLLabServices',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LaboratoryServicesPricelistMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_services_pricelists', to='core.mutationlog')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='medical_pricelist.laboratoryservicespricelist')),
            ],
            options={
                'db_table': 'medical_LaboratoryServicesPricelistMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.CreateModel(
            name='LaboratoryServicesPricelistDetail',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PLLabServiceDetailID', primary_key=True, serialize=False)),
                ('price_overrule', models.DecimalField(blank=True, db_column='PriceOverule', decimal_places=2, max_digits=18, null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('lab_service', models.ForeignKey(db_column='LabServiceID', on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_details', to='medical.laboratoryservice')),
                ('lab_services_pricelist', models.ForeignKey(db_column='PLLabServiceID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='medical_pricelist.laboratoryservicespricelist')),
            ],
            options={
                'db_table': 'tblPLLabServicesDetail',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model, medical_pricelist.models.ItemsOrServicesPricelistDetail),
        ),
    ]
